extends: default

rules:
  document-start: disable
  comments-indentation: disable
  truthy: disable
  line-length: disable
  comments: disable

ignore: |
  helm-libraries/common-library/templates/tests/test-connection.yaml
  **/templates/*.yaml
