{{- include "common-library._deployment.tpl" . }}
---
{{- include "common-library._hpa.tpl" . }}
---
{{- include "common-library._service.tpl" . }}
---
{{- include "common-library._ingress.tpl" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yeahboi-web-app-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  storageClassName: gp2
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: yeahboi-web-app-snapshot
spec:
  schedule: "*/5 * * * *" # Runs every 1 minutes
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: yeahboi-web-app-snapshot
            image: 537239034666.dkr.ecr.ap-southeast-2.amazonaws.com/yeahboi/apps/web-app-snapshot:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: snapshots
              mountPath: /scripts/data
            env:
            - name: GRAFANA_HOST
              value: prometheus-grafana.monitoring.svc.cluster.local
            - name: GRAFANA_PORT
              value: 80
            - name: API_KEY
              value: ***REMOVED***
          volumes:
          - name: snapshots
            persistentVolumeClaim:
              claimName: yeahboi-web-app-snapshot
          restartPolicy: OnFailure
