apiVersion: v2
name: yeahboi-web-app
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common-library
    version: 1.0.2
    repository: oci://537239034666.dkr.ecr.ap-southeast-2.amazonaws.com/yeahboi/helm-libraries