# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: 537239034666.dkr.ecr.ap-southeast-2.amazonaws.com/yeahboi/apps/web-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0297cc4d1c6fc8254a401f204e91b9843fc64cdf

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# imagePullSecrets: 
#   - name: docker-ecr-secret

env: []
  # - name: GRAFANA_HOST
  #   value: yeahboi-web-app-svc.svc.cluster.local
  # - name: GRAFANA_PORT
  #   value: 80

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: true
  # capabilities:
  #   drop:
  #     - ALL

containerPort: 8080  

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  type: ClusterIP
  port: 8080

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  annotations:
    haproxy.org/frontend-config-snippet: http-request redirect code 301 location https://ishans.au%[path] code 301 if { hdr(host) -i www.ishans.au }
  hosts:
    - host: ishans.au
      paths: &paths
        - path: /
          pathType: Prefix
    - host: www.ishans.au
      paths: *paths

  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

resources:
  limits:
    cpu:  50m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
startupProbe:
  httpGet:
    path: /
    port: http
  failureThreshold: 15   # Try 15 times before giving up
  periodSeconds: 3       # Check every 3 seconds (15 * 3 = 45s total max boot time)
  timeoutSeconds: 3
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: snapshots
    persistentVolumeClaim:
      claimName: yeahboi-web-app-snapshot

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: snapshots
    mountPath: /usr/share/nginx/html/data
    readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
