---
loki:
  loki:
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: 2026-01-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ingester:
      chunk_encoding: snappy
    tracing:
      enabled: true
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 2
    storage:
      # Loki requires a bucket for chunks and the ruler.
      # Please provide these values if you are using object storage.
      bucketNames:
        chunks: yeahboi-dev-loki
        ruler: yeahboi-dev-loki
      type: s3
      s3:
        # @schema type:[string, null]
        s3: null
        # @schema type:[string, null]
        endpoint: null
        # @schema type:[string, null]
        region: null
        # @schema type:[string, null]
        secretAccessKey: null
        # @schema type:[string, null]
        accessKeyId: null
        # @schema type:[string, null]
        signatureVersion: v4
        s3ForcePathStyle: false
        insecure: false
        http_config: {}
        # -- Check https://grafana.com/docs/loki/latest/configure/#s3_storage_config for more info on how to provide a backoff_config
        backoff_config: {}
        disable_dualstack: false
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::537239034666:role/allow_loki_s3_access"

  #gateway:
  #  ingress:
  #    enabled: true
  #    hosts:
  #      - host: FIXME
  #        paths:
  #          - path: /
  #            pathType: Prefix

  deploymentMode: Monolithic
  singleBinary:
    replicas: 1
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 50Mi
    extraEnv:
      # Keep a little bit lower than memory limits
      - name: GOMEMLIMIT
        value: 80MiB

  chunksCache:
    # default is 500MB, with limited memory keep this smaller
    writebackSizeLimit: 10MB

  # Enable minio for storage
  minio:
    enabled: false

  # Zero out replica counts of other deployment modes
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0

  monitoring:
    # Dashboards for monitoring Loki
    dashboards:
      # -- If enabled, create configmap with dashboards for monitoring Loki
      enabled: true
    serviceMonitor:
      # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
      enabled: true
      interval: 15s