apiVersion: v2
name: yeahboi-prometheus
version: 1.0.0
description: A Helm chart for Prometheus stack
type: application
dependencies:
  - name: kube-prometheus-stack
    version: 0.17.0
    repository: https://prometheus-community.github.io/helm-charts
# annotations:
  # example: A list of annotations keyed by name (optional).