name: 'Main'

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      web-app: ${{ steps.filter.outputs.web-app }}
      chart-library: ${{ steps.filter.outputs.chart-library }}
      terraform: ${{ steps.changes.outputs.changes }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: Actions/checkout@v6
      - name: Get Paths
        id: paths
        run: ./.github/scripts/get-paths.sh | tee -a "$GITHUB_OUTPUT"
      - name: Path Check
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: ${{ steps.paths.outputs.paths }}
      - name: Output Changes
        id: changes
        run: ./.github/scripts/output-changes.sh ${{ join(fromJson(steps.filter.outputs.changes), ' ') }} | tee -a "$GITHUB_OUTPUT"

  terraform:
    needs: [changes]
    if: needs.changes.outputs.terraform != '[]'
    strategy:
      matrix:
        application: ${{ fromJson(needs.changes.outputs.terraform) }}
    uses: ./.github/workflows/terraform.yaml
    with:
      application: ${{ matrix.application }}
  
  build:
    needs: [changes, terraform]
    uses: ./.github/workflows/build-image.yaml
    if: ${{ needs.changes.outputs.web-app }}
    with:
      application: web-app
      push: ${{ github.ref_name == 'main' && github.event_name == 'push' }}

  helm-libraries:
    needs: [changes]
    if: ${{ needs.changes.outputs.chart-library }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Actions/checkout@v6
        with:
          sparse-checkout: |
            helm-libraries
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::537239034666:role/github_oidc_role
          aws-region: "ap-southeast-2"
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Package & Push
        run: |
          helm package helm-libraries/common-library/ -d helm-libraries/
          # Not require for OCI registries
          # helm repo index helm-libraries --url ${{ steps.login-ecr.outputs.registry }}/yeahboi/helm-libraries/
          helm push helm-libraries/common-library-*.tgz oci://${{ steps.login-ecr.outputs.registry }}/yeahboi/helm-libraries/
