name: 'Terraform'

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:      

jobs:
  vars:
    name: Create github vars
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.inputs.outputs.ENVIRONMENT }}
      region: ${{ steps.inputs.outputs.REGION  }}
      account_id: ${{ steps.inputs.outputs.ACCOUNT_ID }}
      tf_state_bucket: ${{ steps.inputs.outputs.TF_STATE_BUCKET }}
      tf_state_key: ${{ steps.inputs.outputs.TF_STATE_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - id: inputs
        name: Load env vars
        run: tee -a "$GITHUB_OUTPUT" < dev.env


