name: 'Terraform'

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:      

jobs:
  vars:
    name: Create github vars
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.inputs.outputs.ENVIRONMENT }}
      region: ${{ steps.inputs.outputs.REGION  }}
      account_id: ${{ steps.inputs.outputs.ACCOUNT_ID }}
      tf_state_bucket: ${{ steps.inputs.outputs.TF_STATE_BUCKET }}
      tf_state_key: ${{ steps.inputs.outputs.TF_STATE_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - id: inputs
        name: Load env vars
        working-directory: ./terraform
        run: tee -a "$GITHUB_OUTPUT" < dev.env

  lint:
        name: Lint
        needs: [vars]
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v6
    
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v4
            with:
              terraform_version: "~1.14.0"
    
          - name: Terraform Format Check
            working-directory: ./terraform
            run: terraform fmt -check -recursive -diff
            
